version: '3.3'
services:
  frpc:
    image: snowdreamtech/frpc:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: host
    volumes:
      - ./data/frpc.toml:/etc/frp/frpc.toml:ro
    labels:
      createdBy: "Apps"